services:
  # Serviço do Backend Python
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: meu-backend
    ports:
      - "8003:8003"
    volumes:
      - ./backend:/app # Hot-reload em desenvolvimento (opcional)
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:vps%402025_123@172.17.0.1:5432/rrsolucoes_ia

  # Serviço do Frontend React (que você acabou de corrigir)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: meu-frontend
    ports:
      - "8005:8005"
    depends_on:
      - backend
